# generated by Git for Windows
test -f ~/.profile && . ~/.profile

alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'

alias got='git '
alias get='git '
alias gpush='git add . && git commit -m '1' && git push'